// Auto-generated modern catalog
export const books = [
  {
    "id": "1",
    "title": "The Midnight Library",
    "author": "Matt Haig",
    "price": 673,
    "imageUrl": "https://covers.openlibrary.org/b/id/10313767-L.jpg",
    "category": "Fiction",
    "description": "A fantastic fiction book that has captivated millions of readers worldwide. Dive into the incredible world created by Matt Haig.",
    "condition": "New",
    "stock": 13,
    "featured": false,
    "publishedYear": 2020
  },
  {
    "id": "2",
    "title": "Tomorrow, and Tomorrow, and Tomorrow",
    "author": "Gabrielle Zevin",
    "price": 411,
    "imageUrl": "https://covers.openlibrary.org/b/id/12859975-L.jpg",
    "category": "Fiction",
    "description": "A fantastic fiction book that has captivated millions of readers worldwide. Dive into the incredible world created by Gabrielle Zevin.",
    "condition": "New",
    "stock": 7,
    "featured": false,
    "publishedYear": 2022
  },
  {
    "id": "3",
    "title": "Lessons in Chemistry",
    "author": "Bonnie Garmus",
    "price": 197,
    "imageUrl": "https://covers.openlibrary.org/b/id/12725772-L.jpg",
    "category": "Fiction",
    "description": "A fantastic fiction book that has captivated millions of readers worldwide. Dive into the incredible world created by Bonnie Garmus.",
    "condition": "Pre-loved - Excellent",
    "stock": 7,
    "featured": false,
    "publishedYear": 2022
  },
  {
    "id": "4",
    "title": "It Ends With Us",
    "author": "Colleen Hoover",
    "price": 197,
    "imageUrl": "https://covers.openlibrary.org/b/id/10473609-L.jpg",
    "category": "Fiction",
    "description": "A fantastic fiction book that has captivated millions of readers worldwide. Dive into the incredible world created by Colleen Hoover.",
    "condition": "Pre-loved - Good",
    "stock": 13,
    "featured": true,
    "publishedYear": 2012
  },
  {
    "id": "5",
    "title": "Verity",
    "author": "Colleen Hoover",
    "price": 438,
    "imageUrl": "https://covers.openlibrary.org/b/id/8747160-L.jpg",
    "category": "Fiction",
    "description": "A fantastic fiction book that has captivated millions of readers worldwide. Dive into the incredible world created by Colleen Hoover.",
    "condition": "New",
    "stock": 6,
    "featured": false,
    "publishedYear": 2018
  },
  {
    "id": "6",
    "title": "The Seven Husbands of Evelyn Hugo",
    "author": "Taylor Jenkins Reid",
    "price": 238,
    "imageUrl": "https://covers.openlibrary.org/b/id/8354226-L.jpg",
    "category": "Fiction",
    "description": "A fantastic fiction book that has captivated millions of readers worldwide. Dive into the incredible world created by Taylor Jenkins Reid.",
    "condition": "Pre-loved - Excellent",
    "stock": 12,
    "featured": true,
    "publishedYear": 2017
  },
  {
    "id": "7",
    "title": "Normal People",
    "author": "Sally Rooney",
    "price": 158,
    "imageUrl": "https://covers.openlibrary.org/b/id/8794265-L.jpg",
    "category": "Fiction",
    "description": "A fantastic fiction book that has captivated millions of readers worldwide. Dive into the incredible world created by Sally Rooney.",
    "condition": "Pre-loved - Good",
    "stock": 6,
    "featured": false,
    "publishedYear": 2018
  },
  {
    "id": "8",
    "title": "The Song of Achilles",
    "author": "Madeline Miller",
    "price": 400,
    "imageUrl": "https://covers.openlibrary.org/b/id/7098465-L.jpg",
    "category": "Fiction",
    "description": "A fantastic fiction book that has captivated millions of readers worldwide. Dive into the incredible world created by Madeline Miller.",
    "condition": "New",
    "stock": 4,
    "featured": false,
    "publishedYear": 2011
  },
  {
    "id": "9",
    "title": "A Court of Thorns and Roses",
    "author": "Sarah J. Maas",
    "price": 438,
    "imageUrl": "https://covers.openlibrary.org/b/id/8738585-L.jpg",
    "category": "Fiction",
    "description": "A fantastic fiction book that has captivated millions of readers worldwide. Dive into the incredible world created by Sarah J. Maas.",
    "condition": "New",
    "stock": 9,
    "featured": false,
    "publishedYear": 2013
  },
  {
    "id": "10",
    "title": "Dune",
    "author": "Frank Herbert",
    "price": 598,
    "imageUrl": "https://covers.openlibrary.org/b/id/11481354-L.jpg",
    "category": "Science",
    "description": "A fantastic science book that has captivated millions of readers worldwide. Dive into the incredible world created by Frank Herbert.",
    "condition": "New",
    "stock": 8,
    "featured": true,
    "publishedYear": 1965
  },
  {
    "id": "11",
    "title": "Project Hail Mary",
    "author": "Andy Weir",
    "price": 624,
    "imageUrl": "https://covers.openlibrary.org/b/id/11200092-L.jpg",
    "category": "Science",
    "description": "A fantastic science book that has captivated millions of readers worldwide. Dive into the incredible world created by Andy Weir.",
    "condition": "New",
    "stock": 2,
    "featured": false,
    "publishedYear": 2021
  },
  {
    "id": "12",
    "title": "The Martian",
    "author": "Andy Weir",
    "price": 260,
    "imageUrl": "https://covers.openlibrary.org/b/id/11447888-L.jpg",
    "category": "Science",
    "description": "A fantastic science book that has captivated millions of readers worldwide. Dive into the incredible world created by Andy Weir.",
    "condition": "Pre-loved - Good",
    "stock": 4,
    "featured": false,
    "publishedYear": 2011
  },
  {
    "id": "13",
    "title": "Fourth Wing",
    "author": "Rebecca Yarros",
    "price": 427,
    "originalPrice": 597,
    "imageUrl": "https://covers.openlibrary.org/b/id/14407898-L.jpg",
    "category": "Science",
    "description": "A fantastic science book that has captivated millions of readers worldwide. Dive into the incredible world created by Rebecca Yarros.",
    "condition": "New",
    "stock": 9,
    "featured": false,
    "publishedYear": 2023
  },
  {
    "id": "14",
    "title": "The Three-Body Problem",
    "author": "Cixin Liu",
    "price": 197,
    "originalPrice": 275,
    "imageUrl": "https://via.placeholder.com/400x600.png?text=The%20Three-Body%20Problem",
    "category": "Science",
    "description": "A fantastic science book that has captivated millions of readers worldwide. Dive into the incredible world created by Cixin Liu.",
    "condition": "Pre-loved - Excellent",
    "stock": 9,
    "featured": false,
    "publishedYear": 2022
  },
  {
    "id": "15",
    "title": "Atomic Habits",
    "author": "James Clear",
    "price": 516,
    "imageUrl": "https://covers.openlibrary.org/b/id/12539702-L.jpg",
    "category": "Self-Help",
    "description": "A fantastic self-help book that has captivated millions of readers worldwide. Dive into the incredible world created by James Clear.",
    "condition": "New",
    "stock": 10,
    "featured": false,
    "publishedYear": 2016
  },
  {
    "id": "16",
    "title": "The Subtle Art of Not Giving a F*ck",
    "author": "Mark Manson",
    "price": 340,
    "imageUrl": "https://covers.openlibrary.org/b/id/8231990-L.jpg",
    "category": "Self-Help",
    "description": "A fantastic self-help book that has captivated millions of readers worldwide. Dive into the incredible world created by Mark Manson.",
    "condition": "Pre-loved - Good",
    "stock": 14,
    "featured": false,
    "publishedYear": 2016
  },
  {
    "id": "17",
    "title": "Thinking, Fast and Slow",
    "author": "Daniel Kahneman",
    "price": 526,
    "originalPrice": 736,
    "imageUrl": "https://covers.openlibrary.org/b/id/13290711-L.jpg",
    "category": "Business",
    "description": "A fantastic business book that has captivated millions of readers worldwide. Dive into the incredible world created by Daniel Kahneman.",
    "condition": "New",
    "stock": 15,
    "featured": true,
    "publishedYear": 2011
  },
  {
    "id": "18",
    "title": "Outliers",
    "author": "Malcolm Gladwell",
    "price": 310,
    "imageUrl": "https://covers.openlibrary.org/b/id/10021591-L.jpg",
    "category": "Business",
    "description": "A fantastic business book that has captivated millions of readers worldwide. Dive into the incredible world created by Malcolm Gladwell.",
    "condition": "Pre-loved - Excellent",
    "stock": 11,
    "featured": false,
    "publishedYear": 2008
  },
  {
    "id": "19",
    "title": "Sapiens: A Brief History of Humankind",
    "author": "Yuval Noah Harari",
    "price": 567,
    "imageUrl": "https://covers.openlibrary.org/b/id/8634250-L.jpg",
    "category": "History",
    "description": "A fantastic history book that has captivated millions of readers worldwide. Dive into the incredible world created by Yuval Noah Harari.",
    "condition": "New",
    "stock": 5,
    "featured": false,
    "publishedYear": 2011
  },
  {
    "id": "20",
    "title": "Rich Dad Poor Dad",
    "author": "Robert T. Kiyosaki",
    "price": 498,
    "originalPrice": 697,
    "imageUrl": "https://covers.openlibrary.org/b/id/8315603-L.jpg",
    "category": "Business",
    "description": "A fantastic business book that has captivated millions of readers worldwide. Dive into the incredible world created by Robert T. Kiyosaki.",
    "condition": "New",
    "stock": 11,
    "featured": true,
    "publishedYear": 1990
  },
  {
    "id": "21",
    "title": "Deep Work",
    "author": "Cal Newport",
    "price": 322,
    "imageUrl": "https://covers.openlibrary.org/b/id/7988607-L.jpg",
    "category": "Business",
    "description": "A fantastic business book that has captivated millions of readers worldwide. Dive into the incredible world created by Cal Newport.",
    "condition": "Pre-loved - Excellent",
    "stock": 10,
    "featured": false,
    "publishedYear": 2016
  },
  {
    "id": "22",
    "title": "Dare to Lead",
    "author": "Brené Brown",
    "price": 614,
    "originalPrice": 859,
    "imageUrl": "https://covers.openlibrary.org/b/id/7367250-L.jpg",
    "category": "Self-Help",
    "description": "A fantastic self-help book that has captivated millions of readers worldwide. Dive into the incredible world created by Brené Brown.",
    "condition": "New",
    "stock": 11,
    "featured": false,
    "publishedYear": 2012
  },
  {
    "id": "23",
    "title": "Born a Crime",
    "author": "Trevor Noah",
    "price": 551,
    "imageUrl": "https://covers.openlibrary.org/b/id/8294078-L.jpg",
    "category": "History",
    "description": "A fantastic history book that has captivated millions of readers worldwide. Dive into the incredible world created by Trevor Noah.",
    "condition": "New",
    "stock": 6,
    "featured": false,
    "publishedYear": 2016
  },
  {
    "id": "24",
    "title": "Educated",
    "author": "Tara Westover",
    "price": 187,
    "imageUrl": "https://covers.openlibrary.org/b/id/8314077-L.jpg",
    "category": "History",
    "description": "A fantastic history book that has captivated millions of readers worldwide. Dive into the incredible world created by Tara Westover.",
    "condition": "Pre-loved - Excellent",
    "stock": 7,
    "featured": false,
    "publishedYear": 2018
  },
  {
    "id": "25",
    "title": "The Glass Castle",
    "author": "Jeannette Walls",
    "price": 276,
    "imageUrl": "https://covers.openlibrary.org/b/id/11517692-L.jpg",
    "category": "History",
    "description": "A fantastic history book that has captivated millions of readers worldwide. Dive into the incredible world created by Jeannette Walls.",
    "condition": "Pre-loved - Good",
    "stock": 12,
    "featured": false,
    "publishedYear": 2005
  },
  {
    "id": "26",
    "title": "Killers of the Flower Moon",
    "author": "David Grann",
    "price": 697,
    "originalPrice": 975,
    "imageUrl": "https://covers.openlibrary.org/b/id/8055064-L.jpg",
    "category": "History",
    "description": "A fantastic history book that has captivated millions of readers worldwide. Dive into the incredible world created by David Grann.",
    "condition": "New",
    "stock": 13,
    "featured": false,
    "publishedYear": 2017
  },
  {
    "id": "27",
    "title": "Harry Potter and the Sorcerer's Stone",
    "author": "J. K. Rowling",
    "price": 621,
    "imageUrl": "https://covers.openlibrary.org/b/id/15155833-L.jpg",
    "category": "Children",
    "description": "A fantastic children book that has captivated millions of readers worldwide. Dive into the incredible world created by J.K. Rowling.",
    "condition": "New",
    "stock": 12,
    "featured": false,
    "publishedYear": 1997
  },
  {
    "id": "28",
    "title": "Percy Jackson and the Olympians: The Lightning Thief",
    "author": "Rick Riordan",
    "price": 228,
    "imageUrl": "https://covers.openlibrary.org/b/id/7239831-L.jpg",
    "category": "Children",
    "description": "A fantastic children book that has captivated millions of readers worldwide. Dive into the incredible world created by Rick Riordan.",
    "condition": "Pre-loved - Excellent",
    "stock": 3,
    "featured": false,
    "publishedYear": 2005
  },
  {
    "id": "29",
    "title": "The Hunger Games",
    "author": "Suzanne Collins",
    "price": 629,
    "imageUrl": "https://covers.openlibrary.org/b/id/12646537-L.jpg",
    "category": "Children",
    "description": "A fantastic children book that has captivated millions of readers worldwide. Dive into the incredible world created by Suzanne Collins.",
    "condition": "New",
    "stock": 11,
    "featured": false,
    "publishedYear": 2008
  },
  {
    "id": "30",
    "title": "Wonder",
    "author": "R. J. Palacio",
    "price": 297,
    "imageUrl": "https://covers.openlibrary.org/b/id/8223160-L.jpg",
    "category": "Children",
    "description": "A fantastic children book that has captivated millions of readers worldwide. Dive into the incredible world created by R. J. Palacio.",
    "condition": "Pre-loved - Good",
    "stock": 2,
    "featured": false,
    "publishedYear": 2001
  }
];
